version: '3.8'
services:
  database:
    container_name: rrintel
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db_rrintel"
      POSTGRES_PASSWORD: "root"
      POSTGRES_USER: "postgres"
    volumes:
      - db-data:/var/lib/postgresql/data
  redis:
    container_name: backend-redis-1
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  db-data:
  redis_data:
